// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottom: string;
  copyright: string;
  footer: string;
  inner: string;
}
export const cssExports: CssExports;
export default cssExports;
