// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'danger': string;
  'default': string;
  'desc': string;
  'digit': string;
  'disabled': string;
  'empty': string;
  'info': string;
  'infoCard': string;
  'primary': string;
  'secondary': string;
  'squared': string;
  'success': string;
  'title': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
