// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'footer': string;
  'icon': string;
  'income': string;
  'info': string;
  'paymentTransaction': string;
}
export const cssExports: CssExports;
export default cssExports;
