// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activity': string;
  'descr': string;
  'dropdown': string;
  'icon': string;
  'inner': string;
  'item': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
