// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'currency': string;
  'danger': string;
  'default': string;
  'extended': string;
  'features': string;
  'footer': string;
  'header': string;
  'info': string;
  'item': string;
  'itemFeatured': string;
  'period': string;
  'price': string;
  'primary': string;
  'secondary': string;
  'success': string;
  'table': string;
  'title': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
