// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionData': string;
  'borderedBottom': string;
  'description': string;
  'img': string;
  'item': string;
  'large': string;
  'name': string;
  'note': string;
}
export const cssExports: CssExports;
export default cssExports;
