// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'footer': string;
  'icon': string;
  'number': string;
  'sum': string;
}
export const cssExports: CssExports;
export default cssExports;
