// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'descr': string;
  'img': string;
  'imgRemove': string;
  'like': string;
  'oldPrice': string;
  'price': string;
  'productCard': string;
  'selectedLike': string;
  'sizes': string;
  'status': string;
  'statusTitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
