// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  close: string;
  extInput: string;
  livesearch: string;
  livesearchVisible: string;
  logo: string;
  logoContainer: string;
  option: string;
  optionCheckbox: string;
  options: string;
  result: string;
  resultContent: string;
  resultSource: string;
  resultText: string;
  resultThumb: string;
  resultsTitle: string;
  searchInput: string;
  suggestion: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
