// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fullScreen': string;
  'hidden': string;
  'loader': string;
}
export const cssExports: CssExports;
export default cssExports;
