// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'head': string;
  'line': string;
  'lineDescr': string;
  'name': string;
  'note': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
