// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'controls': string;
  'footer': string;
  'header': string;
  'layout': string;
  'light': string;
  'logo': string;
  'navigation': string;
  'navigationActive': string;
  'navigationItems': string;
}
export const cssExports: CssExports;
export default cssExports;
