// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'container': string;
  'description': string;
  'item': string;
  'itemLabel': string;
  'settings': string;
  'settingsOpened': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
