// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'dropdown': string;
  'menuIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
