// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buyPro': string;
  'icon': string;
  'light': string;
  'logo': string;
  'logoContainer': string;
  'menu': string;
  'navigation': string;
  'scrollbarDesktop': string;
  'scrollbarMobile': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
