// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'form': string;
  'inner': string;
  'login': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
