name: admin-ui-sandbox CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn
      run: yarn install
    - name: Tsc
      run: yarn tsc     
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test    
    - name: Build Local
      run: yarn build
    - name: Audit
      run: |
        npm i --package-lock-onl  
        npm audit
      env:
        CI: true
